### ISSUE TITLE
Add AS923_1C plan when available

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-pktfwd#118]
Helium are adding an AS923_1C plan.

![Screenshot_20230123_002848_Discord](https://user-images.githubusercontent.com/3359418/213948930-eb5c5d7c-eb5b-4059-933f-f6572e4247a1.jpg)
![Screenshot_20230123_002906_Discord](https://user-images.githubusercontent.com/3359418/213948935-bce487b6-df8e-4818-bd2a-f87a24b5b410.jpg)

Link: https://discord.com/channels/404106811252408320/813452716286017557/1062114939684278382

**Comment by shawaj** [comment]
Looks like we can add it immediately - https://github.com/helium/sx1302_hal/pull/36/files

**Comment by shawaj** [comment]
Seems they have EU868_A to _F and AS923-1_A to _F also and a

**Comment by MuratUrsavas** [comment]
@shawaj I got this :+1:  (NEBD-71)

**Comment by shawaj** [comment]
Nice one :-)

Think they may have updated some others too and now there is this AU915 reboot too 🤦

**Comment by MuratUrsavas** [comment]
We can keep our settings in sync with upstream and follow them closely.
