### ISSUE TITLE
packet-forwarder unable to start if interface wlan0 is not present

### ISSUE THREAD

**Issue by ctlynx** [NebraLtd/hm-pktfwd#140]
**Problem:**
if `/sys/class/net/wlan0/address` does not exist, then pktfwd fails and is unable to start.

**Error:**
```
Traceback (most recent call last):
  File "/opt/pktfwd-dependencies/hm_pyhelper/miner_param.py", line 323, in get_ethernet_addresses
    diagnostics[key] = get_mac_address(path)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pktfwd-dependencies/hm_pyhelper/miner_param.py", line 350, in get_mac_address
    raise MinerFailedToFetchMacAddress("Failed to find file"
  File "/opt/pktfwd-dependencies/hm_pyhelper/miner_param.py", line 344, in get_mac_address
    file = open(path)
           ^^^^^^^^^^
hm_pyhelper.exceptions.MinerFailedToFetchMacAddress: Failed to find filecontaining miner mac address. Exception: [Errno 2] No such file or directory: '/sys/class/net/wlan0/address'
```
Log file: [nebra-error-log.txt](https://github.com/NebraLtd/hm-pktfwd/files/11265788/nebra-error-log.txt)
 
**Cause:**
Method [`get_ethernet_addresses`](https://github.com/NebraLtd/hm-pyhelper/blob/431c825963a8d13d96fdf5ff73953e0bcb27a1eb/hm_pyhelper/miner_param.py#L311) raises `MinerFailedToFetchMacAddress` and [`populate_local_conf_template`](https://github.com/NebraLtd/hm-pktfwd/blame/ac1c1b518e442e4ddd194f05ff5e7740f06f9092/pktfwd/utils.py#L121) fails even if the MAC of `eth0` could be obtained.

I suppose that [`get_ethernet_addresses`](https://github.com/NebraLtd/hm-pyhelper/blob/431c825963a8d13d96fdf5ff73953e0bcb27a1eb/hm_pyhelper/miner_param.py#L311) should not fail and simply return the MAC addresses that do exist.
 
**Expected behavior:**
Miner should be able to startup and operate using `eth0` MAC address as before.

It may happen that `wlan0` does not exist if wifi dongle is broken or unplugged. 
On the device I detected the problem, `wlan0` does not exist because the dongle is broken. I have not replaced it with a new one because it does not use wifi. So far it was working well connected via ethernet. The dashboard showed that there was no MAC address for wifi, but it worked ok.

**Comment by HelPi7** [comment]
Having the same issue!

**Comment by shawaj** [comment]
Thanks @HelPi7 @ctlynx we're working on a fix.

Also related to https://github.com/NebraLtd/hm-diag/issues/557

**Comment by robputt** [comment]
See https://nebraltd.atlassian.net/browse/NEBD-181
