### ISSUE TITLE
Rssi too strong compared to other hotspots

### ISSUE THREAD

**Issue by disk91** [NebraLtd/hm-pktfwd#16]
At least for Europe, RSSI reported by some Nebra hotspot is really high compared to other nearest hotspot. As a consequence, the Nebra hotspot get Join Accept, ack and donwlink messages to process. This is applicable to hotspot used with outdoor antennas.
As an example, I've seen -80dBm > -90dBm over 13.8km. Free space path loss for 13.8km is 100dBm confirming the Nebra Rssi to be valid for 14dBm, but the problem it is really higher than the others.

Other hotspots are reporting for the same mesage:
- 7km / -118dBm (outdoor rak DiY)
- 8km / -115dBm (outdoor Rak hotspot)
- 8km / -107dBm (outdoor Rak hotspot)
Compared to Nebra
- 13,8km / -89dBm

As a consequence, since this Nebra is up, there is a real difficulty for devices in the city to join the network and receiving Ack.

**Comment by shawaj** [comment]
Do you have further details of the hotspots in question so we can take a further look at them on the network?

**Comment by disk91** [comment]
Take a look at Spare Lemon Urchin

**Comment by shawaj** [comment]
> Take a look at Spare Lemon Urchin

For reference
https://explorer.helium.com/hotspots/11RRgLVeh7eigMp8wurCn4pCjfxhfk5iFz4CioP3MuYfmCapbv8/activity

@disk91 I don't see however that this is an issue with our concentrators, more what helium considers to be a valid witness in their acceptance curves

**Comment by shawaj** [comment]
Interesting reading here also - people with other hardware with similar issues https://github.com/helium/miner/issues/618

**Comment by rbrtio** [comment]
This may be impacted by the use, or lack of, a saw filter on the concentrator as they are generally introduce quite a bit of loss.

Another potential source of the issue is that some devices report rssi vs other that report rssis, which can be vastly different figures.
