### ISSUE TITLE
Why are we using v1.0.5 of sx1302_hal? 

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-pktfwd#24]
https://github.com/NebraLtd/hm-pktfwd/blob/1156718fcf1308a96f9171d0098f82daa7358eac/buildfiles/compileSX1302.sh#L5-L7

Why are we using v1.0.5 instead of latest v2.1.0?

Relates to https://github.com/NebraLtd/sx1302_hal/issues/1 and https://github.com/NebraLtd/packet_forwarder/issues/1 and https://github.com/NebraLtd/hm-pktfwd/issues/23

If there is a specific reason we should document it

**Comment by vpetersson** [comment]
We haven't made it to this repo yet. We're working on rewriting `hm-diag` and `hm-config` atm.

**Comment by shawaj** [comment]
no worries - was just putting down some comments / things i noticed in my travels so i didn't forget!
