### ISSUE TITLE
AS923_1 asserted cause lora operational false

### ISSUE THREAD

**Issue by hollejacklin** [NebraLtd/hm-pktfwd#53]
I got two new nebra indoor miner 2021/9/27. I power on the first one, and local diagnostic showed all ok. However the local diagnostic showed lora operational error after the region asserted to AS923_1.
I power on the another one. The local diagnostic showed all ok in the beginning, and then the lora operational became false, after AS923_1 was asserted to region.
Please check this issue. my ticket 282366

**Comment by shawaj** [comment]
@hollejacklin thanks for reporting this. A fix is coming in #54

**Comment by shawaj** [comment]
Testing the fix now https://github.com/NebraLtd/helium-miner-software/commit/561767f8d3c8ef27ac61b214e7ce1efbfa81823a

**Comment by shawaj** [comment]
Config working now - just going to give it a few hours before merging to mainnet

**Comment by shawaj** [comment]
PR here https://github.com/NebraLtd/helium-miner-software/pull/158

**Comment by shawaj** [comment]
@hollejacklin should be fixed now 👍

**Comment by hollejacklin** [comment]
Yes it work. well done
