### ISSUE TITLE
Lora Operational FALSE

### ISSUE THREAD

**Issue by EmielN** [NebraLtd/hm-pktfwd#76]
Lora Opartional FALSE, and not responding on intern ip adres now , not syncing. 

Worked for exactly 7 days and then down, the location is asserted right and the region is asserted. Any solving for this, because totally no response from helpdesk Nebra. 

<img width="504" alt="Schermafbeelding 2021-11-23 om 18 49 19" src="https://user-images.githubusercontent.com/95448526/144509100-cd44c5e0-1255-4495-9382-5a6a972cfcd7.png">

**Comment by shawaj** [comment]
This is not a support channel.

Please email support@nebra.com
