### ISSUE TITLE
Support all lora concentrators used by Bobcat

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-pktfwd#83]
Confirm all variants that need to be supported.

- sx1301
- 1302
- 1308

**Notes**
- Currently using sx1302 chip_id script: https://github.com/NebraLtd/sx1302_hal/tree/master/util_chip_id
- Checking from pktfwd: https://github.com/NebraLtd/hm-pktfwd/blob/77bfb4205602e93867e833f4b54d1058e5c65df7/pktfwd/utils.py#L73

**Comment by shawaj** [comment]
I believe sx1308 uses the same HAL as sx1301 so should already be supported as are the others

**Comment by shawaj** [comment]
Closing this as already supported
