### ISSUE TITLE
Join accept sending in wrong channel

### ISSUE THREAD

**Issue by CanEmreUnal** [NebraLtd/hm-pktfwd#91]
Device tries to connect to hotspot within US915 freq channel but join accept is sending back by hotspot to the device in EU868.

Packet-forwarder conf seems fine. 

Hotspot is located in EU.

- What kind of mechanism behind is selecting the right frequency plan ?
- Could moving the hotspot to the US might be fix it ?

```
[Logs]    [2022-5-23 1:17:43] [packet-forwarder] JSON down: {"txpk":{"codr":"4/5","data":"ILvNqFA9lCMJWaQRXf/xc28=","datr":"SF9BW125","freq":867.2999877929688,"imme":false,"ipol":true,"modu":"LORA","powe":20,"rfch":0,"size":17,"tmst":1784173964}}
[Logs]    [2022-5-23 1:17:43] [packet-forwarder] ERROR: Packet REJECTED, unsupported frequency - 867299987 (min:902000000,max:928000000)
```

![console](https://user-images.githubusercontent.com/17678145/169718737-26ed6d87-76b7-4969-bce1-080f2c20baed.png)

**Comment by MuratUrsavas** [comment]
Hi @CanEmreUnal,

This repository is a fork of original packet forwarder for our internal use. Therefore it's not a support forum. If you have a Nebra device and have issues, please contact with our support team. If your device is not a Nebra one, please contact with your manufacturer.

If you think packet forwarder has a bug in source code, please open a ticket in the upstream repo (https://github.com/Lora-net/packet_forwarder)
